#!/usr/bin/env python3
"""Generate hand/include/hand/theme/themes.gen.hpp from the iterm2-color-schemes
ghostty format. One constexpr NamedTheme per scheme.

Regenerate:
    git clone --depth 1 https://github.com/mbadolato/iterm2-color-schemes /tmp/iterm2cs
    python3 tools/gen_themes.py include/hand/theme/themes.gen.hpp
(Set ITERM2CS=/path to point at a different checkout.)
"""
import os, re, sys, glob

SRC = os.environ.get("ITERM2CS", "/tmp/iterm2cs") + "/ghostty"
OUT = sys.argv[1] if len(sys.argv) > 1 else "include/hand/theme/themes.gen.hpp"

def hexrgb(h):
    h = h.strip().lstrip('#')
    return int(h[0:2], 16), int(h[2:4], 16), int(h[4:6], 16)

def slug(name):
    s = name.lower()
    s = re.sub(r"[^a-z0-9]+", "-", s).strip("-")
    return s

def parse(path):
    pal = {}
    bg = fg = cur = sel = None
    for line in open(path, encoding="utf-8", errors="replace"):
        line = line.strip()
        m = re.match(r"palette\s*=\s*(\d+)\s*=\s*(#?[0-9a-fA-F]{6})", line)
        if m:
            pal[int(m.group(1))] = hexrgb(m.group(2)); continue
        m = re.match(r"(\S[\w-]*)\s*=\s*(#?[0-9a-fA-F]{6})", line)
        if not m:
            continue
        k, v = m.group(1), hexrgb(m.group(2))
        if k == "background": bg = v
        elif k == "foreground": fg = v
        elif k == "cursor-color": cur = v
        elif k == "selection-background": sel = v
    if len(pal) < 16 or bg is None or fg is None:
        return None
    return pal, bg, fg, cur or fg, sel or pal.get(8, fg)

def lum(c):
    r, g, b = c
    return (0.2126*r + 0.7152*g + 0.0722*b) / 255.0

def esc(s):
    return s.replace('\\', '\\\\').replace('"', '\\"')

def C(c):
    return f"C({c[0]:#04x},{c[1]:#04x},{c[2]:#04x})"

themes = []
for path in sorted(glob.glob(os.path.join(SRC, "*"))):
    if not os.path.isfile(path):
        continue
    name = os.path.basename(path)
    r = parse(path)
    if r is None:
        continue
    pal, bg, fg, cur, sel = r
    dark = lum(bg) < 0.5
    # Brand accent: prefer the (bright) blue index for dark themes, mauve/blue
    # for light. Fall back to the selection colour if the blue is too dim.
    accent = pal.get(12) or pal.get(4) or fg
    if lum(accent) < 0.15:
        accent = pal.get(4, fg)
    themes.append((slug(name), name, dark, bg, fg, cur, sel, accent, pal))

# De-dup slugs (some names collide after slugging).
seen = {}
uniq = []
for t in themes:
    s = t[0]
    if s in seen:
        seen[s] += 1
        t = (f"{s}-{seen[s]}",) + t[1:]
    else:
        seen[s] = 0
    uniq.append(t)
themes = uniq

os.makedirs(os.path.dirname(OUT), exist_ok=True)
with open(OUT, "w") as o:
    o.write("// SPDX-License-Identifier: LGPL-2.0-or-later\n")
    o.write("//\n// GENERATED by hand/tools/gen_themes.py from\n")
    o.write("// https://github.com/mbadolato/iterm2-color-schemes (ghostty format).\n")
    o.write("// Do not edit by hand; re-run the generator to refresh.\n//\n")
    o.write(f"// {len(themes)} themes.\n\n")
    o.write("#ifndef HAND_THEME_THEMES_GEN_HPP\n#define HAND_THEME_THEMES_GEN_HPP\n\n")
    o.write('#include "hand/theme/named_theme.hpp"\n\n')
    o.write("namespace hand::themes {\n\n")
    o.write("using toe::Rgb;\n")
    o.write("inline constexpr Rgb C(int r, int g, int b) {\n")
    o.write("    return Rgb{static_cast<std::uint8_t>(r), static_cast<std::uint8_t>(g),\n")
    o.write("              static_cast<std::uint8_t>(b)};\n}\n\n")
    o.write(f"inline constexpr NamedTheme kBuiltins[] = {{\n")
    for (sid, name, dark, bg, fg, cur, sel, accent, pal) in themes:
        ansi = ", ".join(C(pal[i]) for i in range(16))
        o.write(f'    {{"{esc(sid)}", "{esc(name)}", {"true" if dark else "false"},\n')
        o.write(f'     {C(bg)}, {C(fg)}, {C(cur)}, {C(sel)}, {C(accent)},\n')
        o.write(f'     {{{ansi}}}}},\n')
    o.write("};\n\n")
    o.write("inline constexpr int kBuiltinCount = "
            f"static_cast<int>(sizeof(kBuiltins) / sizeof(kBuiltins[0]));\n\n")
    o.write("} // namespace hand::themes\n\n")
    o.write("#endif // HAND_THEME_THEMES_GEN_HPP\n")

print(f"wrote {OUT}: {len(themes)} themes")
